name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - master

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
    - name: Checkout my repo code
      uses: actions/checkout@v2
    
    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17.0.11'
        distribution: 'temurin'
    
    # Step 3: Install Flutter
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    # Step 4: Setup Ruby
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3.6"
        bundler-cache: true
        working-directory: android

    # Step 5: Add Linux platform to Gemfile.lock
    - name: Add Linux platform to Gemfile.lock
      run: |
        bundle lock --add-platform x86_64-linux
      working-directory: android

    # Step 6: Build and Distribute App
    - name: Build and Distribute App
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: |
        bundle exec fastlane android firebase_distrebution_newaapp
      working-directory: android
